version: "3.7"

services:
  node:
    image: node-app-ci
    container_name: node
    hostname: node
    build:
      context: app
      dockerfile: Dockerfile
    command: node /app/index.js
    ports:
      - 2080:3000
    networks:
      - CI
    links:
      - mariadb
    volumes:
      - type: volume
        source: app
        target: /app

  mariadb:
    image: mariadb
    container_name: mariadb
    hostname: mariadb
    ports:
      - 4407:3306
    networks:
      - CI
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: $PWD/mariadb-server.cnf
        target: /etc/mysql/mariadb.conf.d/50-server.cnf
    environment:
      MARIADB_ROOT_PASSWORD: P4ssw0rd
      MARIADB_USER: mariadb
      MARIABD_PASWORD: P4ssw0rd
      MARIADB_DATABASE: Mini

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    networks:
      - CI
    links:
      - mariadb

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    hostname: jenkins
    ports:
      - 1080:8080
    networks:
      - CI
    volumes:
      - type: bind
        source: $PWD/jenkins_home
        target: /var/jenkins_home
          
volumes:
  dbdata:
  app:
  jenkins_home:

networks:
  CI:
    name: CI
    driver: bridge
    