version: "3"

services:
  node:
    image: bitnami/express
    container_name: node
    hostname: node
    command: node /app/index.js
    links:
      - mariadb
    volumes:
      - type: volume
        source: app
        target: /app
        volume:
          nocopy: true

  mariadb:
    image: mariadb
    container_name: mariadb
    hostname: mariadb
    ports:
      - 4407:3306
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: $PWD/mariadb-server.cnf
        target: /etc/mysql/mariadb.conf.d/50-server.cnf
    environment:
      MARIADB_ROOT_PASSWORD: P4ssw0rd
      MARIADB_USER: mariadb
      MARIABD_PASWORD: P4ssw0rd
      MARIADB_DATABASE: Mini
  
  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    links:
      - mariadb
  
volumes:
  dbdata:
  app:
